services:
  - type: web
    name: ARCTURUS-Bot
    runtime: python
    plan: free
    region: frankfurt
    branch: main
    
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 120 bot:app
    
    healthCheckPath: /health
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      
      - key: BOT_TOKEN
        sync: false
      
      - key: ADMIN_ID
        sync: false
      
      - key: CHANNEL_USERNAME
        sync: false
      
      - key: WEBAPP_URL
        sync: false
      
      - key: RENDER_URL
        sync: false